name: Ruby
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.6'
          - '2.7.7'
          - '3.0.0'
          - '3.0.1'
          - '3.0.2'
          - '3.0.3'
          - '3.0.4'
          - '3.0.5'
          - '3.1.0'
          - '3.1.1'
          - '3.1.2'
          - '3.1.3'
          - '3.2.0'
          - '3.2.1'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
